# Generated by Django 5.2.4 on 2025-08-01 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ingro',
            new_name='intro',
        ),
    ]
